import type { Kind } from './core';
type Section = { title: string; items: string[] };
export const rules: Record<Kind, { name: string; subtitle: string; goal: string; sections: Section[]; source?: string }> = {
  durak: { name:'Durak', subtitle:'Duell · 36 Karten', goal:'Werde deine Karten los, sobald der Nachziehstapel leer ist.', source:'https://www.pagat.com/beating/podkidnoy_durak.html', sections:[
    {title:'Dein Zug',items:['Angreifen: Lege eine Karte. Danach darfst du Werte nachlegen, die bereits auf dem Tisch liegen.','Verteidigen: Lege eine höhere Karte derselben Farbe oder einen Trumpf. Trumpf schlägt nur höherer Trumpf.','Du kannst nicht decken? Nimm die Karten auf.']},
    {title:'Der Stapel',items:['Sechs Startkarten. Die offene Karte unter dem Stapel zeigt Trumpf.','Nach dem Angriff zieht zuerst der Angreifer, dann der Verteidiger auf sechs Karten nach. Die Trumpfkarte kommt zuletzt.']},
    {title:'Gut zu wissen',items:['Maximal sechs Angriffe, nie mehr als der Verteidiger zu Beginn Karten hatte.','Nach „Aufnehmen“ darf noch nachgeworfen werden. Nach erfolgreicher Abwehr wechseln die Rollen; nach dem Aufnehmen bleibt der Angreifer.','Kein Weitergeben. Sind beide Hände gleichzeitig leer, endet die Runde unentschieden.']}
  ]},
  arschloch: { name:'Arschloch', subtitle:'Viererrunde · 52 Karten', goal:'Leere deine Hand vor den anderen. Wer zuletzt übrig bleibt, ist das Arschloch.', source:'https://www.pagat.com/climbing/president.html', sections:[
    {title:'Karten legen',items:['Wähle eine Karte oder mehrere Karten mit gleichem Wert.','Überbiete mit genau derselben Anzahl und einem höheren Wert. Oder passe.','Reihenfolge: 3 → 4 → 5 → 6 → 7 → 8 → 9 → 10 → B → D → K → A → 2.']},
    {title:'Neu eröffnen',items:['Passen alle anderen, wird der Tisch frei. Wer zuletzt gelegt hat, eröffnet. Ist dessen Hand leer, beginnt der nächste Spieler mit Karten.','Nach dem Passen darfst du beim nächsten Umlauf wieder mitspielen.']},
    {title:'Nächste Runde',items:['Alle 52 Karten werden verteilt. Du eröffnest die erste Runde.','Danach gibt das Arschloch seine höchste Karte an den Sieger. Der Sieger gibt eine beliebige Karte zurück und beginnt.','Keine Joker, Revolution oder Sonderwirkung der 2.']}
  ]},
  neunern: { name:'Neunerln', subtitle:'Viererrunde · 36 Karten', goal:'Lege als Erster deine letzte Karte ab.', sections:[
    {title:'So legst du ab',items:['Fünf Startkarten. Lege dieselbe Farbe oder denselben Wert wie die oberste Karte.','Eine 9 darfst du auf jede Karte legen – außer bei einer offenen Ziehstrafe. Wähle anschließend die nächste Farbe.','Nichts passt? Ziehe eine Karte. Passt sie, darfst du sie direkt legen; sonst geht es weiter.']},
    {title:'Die Sonderkarten',items:['7 → Der nächste Spieler zieht zwei Karten. Eine weitere 7 gibt die Strafe weiter und erhöht sie um zwei.','8 → Der nächste Spieler setzt aus.','9 → Du wählst Kreuz, Karo, Herz oder Pik.']},
    {title:'Klopfen & Punkte',items:['Vor dem Ablegen deiner vorletzten Karte musst du auf den Tisch klopfen. Tippe dafür auf die Tischfläche oder nutze die Klopfen-Taste.','Vergessen? Deine letzte Karte bleibt gesperrt. Du ziehst zwei Strafkarten; eine offene 7er-Strafe kommt dazu. Danach geht es beim nächsten Spieler weiter.','Jede Restkarte zählt einen Minuspunkt. Gewinnt jemand mit einer 9 als letzter Karte, werden die Minuspunkte aller Mitspieler verdoppelt. Der Punktestand bleibt über mehrere Runden erhalten.']},
    {title:'Unsere Hausregeln',items:['36 Karten von 6 bis Ass. Die erste offene Karte hat keinen Sondereffekt.','Nach dem Ziehen einer Strafe endet dein Zug. Der Ablagestapel wird bei Bedarf neu gemischt; die oberste Karte bleibt liegen.','Du darfst mit einer Sonderkarte gewinnen, wenn du vorher rechtzeitig geklopft hast.','Ist der Stapel leer und kann eine volle Runde niemand legen, gewinnt die kleinste Hand.']}
  ]},
  poker: { name:'Poker', subtitle:'Texas Hold’em · Duell', goal:'Gewinne die Chips im Pot: mit der besten Hand oder indem dein Gegner passt.', source:'https://www.pokerstars.com/poker/games/texas-holdem/', sections:[
    {title:'Deine Möglichkeiten',items:['Checken: ohne Einsatz weiter, wenn noch nichts zu zahlen ist.','Mitgehen: den angezeigten Betrag bezahlen. Passen: diese Hand aufgeben.','Erhöhen: Einsatzregler öffnen, Betrag wählen und bestätigen. All-in setzt alle deine übrigen Chips.']},
    {title:'Die Karten',items:['Du bekommst zwei eigene Karten. In die Mitte kommen erst drei Karten (Flop), dann eine (Turn), dann eine (River).','Die besten fünf aus deinen zwei und den fünf gemeinsamen Karten zählen. Gleiche Hände teilen den Pot.']},
    {title:'Welche Hand gewinnt?',items:['Von stark nach schwach: Straight Flush · Vierling · Full House · Flush · Straße · Drilling · Zwei Paare · Paar · Hohe Karte.','Bei Gleichstand entscheidet die höchste übrige Karte. Das Ass kann in A–2–3–4–5 niedrig zählen.']},
    {title:'Einsätze und Ablauf',items:['1.000 Spielchips pro Person. Blinds 10 / 20, Button wechselt jede Hand. Vor dem Flop beginnt der Small Blind, danach der Big Blind.','Mindesterhöhung: letzte volle Erhöhung, mindestens 20. Ein kleineres All-in eröffnet das Erhöhen nicht erneut. Nicht mitgegangene Chips erhältst du zurück.','Nur Spielchips. Die Bots kennen weder deine Hand noch die kommenden Karten.']}
  ]}
};
