import type { Kind } from './core';
type Section = { title: string; items: string[] };
export const rules: Record<Kind, { name: string; subtitle: string; goal: string; sections: Section[]; source?: string }> = {
  durak: { name:'Durak', subtitle:'Duell · 36 Karten', goal:'Werde deine Karten los, sobald der Nachziehstapel leer ist.', source:'https://www.pagat.com/beating/podkidnoy_durak.html', sections:[
    {title:'Dein Zug',items:['Angreifen: Lege eine Karte. Danach darfst du Werte nachlegen, die bereits auf dem Tisch liegen.','Verteidigen: Lege eine höhere Karte derselben Farbe oder einen Trumpf. Einen Trumpf schlägt nur ein höherer Trumpf.','Schieben: Hast du denselben Wert wie die offene Angriffskarte, kannst du ihn dazulegen. Der bisherige Angreifer muss anschließend alle offenen Karten decken.','Du kannst weder decken noch schieben? Nimm die Karten auf.']},
    {title:'Der Stapel',items:['Sechs Startkarten. Die offene Karte unter dem Stapel zeigt die Trumpffarbe.','Nach dem Angriff zieht zuerst der Angreifer, dann der Verteidiger auf sechs Karten nach. Die Trumpfkarte kommt zuletzt.']},
    {title:'Gut zu wissen',items:['Es sind höchstens sechs Angriffskarten erlaubt, jedoch nie mehr, als der Verteidiger zu Beginn des Angriffs auf der Hand hatte. Das gilt auch beim Schieben.','Nach „Aufnehmen“ darf noch nachgeworfen werden. Nach erfolgreicher Abwehr wechseln die Rollen; nach dem Aufnehmen bleibt der Angreifer.','Sind beide Hände gleichzeitig leer, endet die Runde unentschieden.']}
  ]},
  arschloch: { name:'Arschloch', subtitle:'Viererrunde · 52 Karten', goal:'Leere deine Hand vor den anderen. Wer zuletzt übrig bleibt, ist das Arschloch.', source:'https://www.pagat.com/climbing/president.html', sections:[
    {title:'Karten legen',items:['Wähle eine Karte oder mehrere Karten mit gleichem Wert.','Überbiete mit genau derselben Anzahl und einem höheren Wert. Oder passe.','Reihenfolge: 3 → 4 → 5 → 6 → 7 → 8 → 9 → 10 → B → D → K → A → 2.']},
    {title:'Neu eröffnen',items:['Passen alle anderen, wird der Tisch frei. Wer zuletzt gelegt hat, eröffnet. Ist dessen Hand leer, beginnt der nächste Spieler, der noch Karten hat.','Nach dem Passen darfst du beim nächsten Umlauf wieder mitspielen.']},
    {title:'Nächste Runde',items:['Alle 52 Karten werden verteilt. Du eröffnest die erste Runde.','Danach gibt das Arschloch seine höchste Karte an den Sieger. Der Sieger gibt eine beliebige Karte zurück und beginnt.','Es gibt keine Joker, keine Revolution und keine zusätzliche Sonderwirkung der 2.']}
  ]},
  neunern: { name:'Neunerln', subtitle:'Viererrunde · 36 Karten', goal:'Lege als Erster deine letzte Karte ab.', sections:[
    {title:'So legst du ab',items:['Fünf Startkarten. Lege dieselbe Farbe oder denselben Wert wie die oberste Karte.','Eine 9 darfst du auf jede Karte legen – außer bei einer offenen Ziehstrafe. Wähle anschließend die nächste Farbe.','Nichts passt? Ziehe eine Karte. Passt sie, darfst du sie direkt legen; sonst geht es weiter.']},
    {title:'Die Sonderkarten',items:['7 → Der nächste Spieler zieht zwei Karten. Eine weitere 7 gibt die Strafe weiter und erhöht sie um zwei.','8 → Der nächste Spieler setzt aus.','9 → Du wählst Kreuz, Karo, Herz oder Pik.']},
    {title:'Klopfen & Punkte',items:['Vor dem Ablegen deiner vorletzten Karte musst du auf den Tisch klopfen. Tippe dafür auf die Tischfläche oder nutze die Klopfen-Taste.','Vergessen? Deine letzte Karte bleibt gesperrt. Du ziehst zwei Strafkarten; eine offene 7er-Strafe kommt dazu. Danach geht es beim nächsten Spieler weiter.','Jede Restkarte zählt einen Minuspunkt. Gewinnt jemand mit einer 9 als letzter Karte, werden die Minuspunkte aller Mitspieler verdoppelt. Der Punktestand bleibt über mehrere Runden erhalten.']},
    {title:'Unsere Hausregeln',items:['36 Karten von 6 bis Ass. Die erste offene Karte hat keinen Sondereffekt.','Nach dem Ziehen einer Strafe endet dein Zug. Der Ablagestapel wird bei Bedarf neu gemischt; die oberste Karte bleibt liegen.','Du darfst mit einer Sonderkarte gewinnen, wenn du vorher rechtzeitig geklopft hast.','Ist der Stapel leer und kann eine ganze Runde lang niemand eine Karte legen, gewinnt die kleinste Hand.']}
  ]},
  poker: { name:'Poker', subtitle:'Texas Hold’em · Duell', goal:'Gewinne die Chips im Pot: mit der besten Hand oder indem dein Gegner passt.', source:'https://www.pokerstars.com/poker/games/texas-holdem/', sections:[
    {title:'Deine Möglichkeiten',items:['Checken: ohne Einsatz weiterspielen, wenn noch nichts zu zahlen ist.','Mitgehen: den angezeigten Betrag bezahlen. Passen: diese Hand aufgeben.','Erhöhen: Einsatzregler öffnen, Betrag wählen und bestätigen. Mit All-in setzt du alle deine übrigen Chips.']},
    {title:'Die Karten',items:['Du bekommst zwei eigene Karten. In die Mitte kommen erst drei Karten (Flop), dann eine (Turn), dann eine (River).','Es zählen die besten fünf Karten aus deinen zwei Handkarten und den fünf Gemeinschaftskarten. Gleich starke Hände teilen den Pot.']},
    {title:'Welche Hand gewinnt?',items:['Von stark nach schwach: Straight Flush · Vierling · Full House · Flush · Straße · Drilling · Zwei Paare · Paar · Hohe Karte.','Bei Gleichstand entscheidet die höchste übrige Karte. Das Ass kann in A–2–3–4–5 niedrig zählen.']},
    {title:'Einsätze und Ablauf',items:['1.000 Spielchips pro Person. Die Blinds liegen bei 10 / 20, der Button wechselt nach jeder Hand. Vor dem Flop handelt der Small Blind zuerst; ab dem Flop beginnt der Big Blind.','Die Mindesterhöhung entspricht der letzten vollen Erhöhung, beträgt jedoch mindestens 20 Chips. Ein kleineres All-in gibt Spielern, die bereits gehandelt haben, kein neues Recht auf eine weitere Erhöhung. Nicht mitgegangene Chips erhältst du zurück.','Es wird ausschließlich mit Spielchips gespielt. Die Bots kennen weder deine Hand noch die kommenden Karten.']}
  ]}
};
